function [ freq, SUNGND_DIF, SUNGNDOBS_DIR, OBSGND_EMBED, OBSGND_DIRECT, SPHERICAL] = load_acd( filename )
%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/wrightla/Documents/Modtran/Mod5.3.2.Mac/SIM_NEON_Oct2014/Cirrus10.acd
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/04/07 14:47:18

% Initialize variables.
% filename = '/Users/wrightla/Documents/Modtran/Mod5.3.2.Mac/SIM_NEON_Oct2014/Cirrus10.acd';
startRow = 6;

% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
% For more information, see the TEXTSCAN documentation.
% formatSpec = '%9f%4f%4f%13f%15f%14f%14f%14f%f%[^\n\r]';
formatSpec = '%9f%4f%4f%13f%15f%14f%14f%14f%f';

% Open the text file.
fileID = fopen(filename,'r');

% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

% Close the text file.
fclose(fileID);

% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

% Allocate imported array to column variable names
freq = dataArray{:, 1};
los = dataArray{:, 2};
kint = dataArray{:, 3};
kweight = dataArray{:, 4};
SUNGND_DIF = dataArray{:, 5};
SUNGNDOBS_DIR = dataArray{:, 6};
OBSGND_EMBED = dataArray{:, 7};
OBSGND_DIRECT = dataArray{:, 8};
SPHERICAL = dataArray{:, 9};

% Clear temporary variables
%clearvars filename startRow formatSpec fileID dataArray ans;
clear filename startRow formatSpec fileID dataArray ans;


end

